#!/usr/bin/env bash
#
# Builds the release source archive for a tag and prints the release notes
# to stdout. The archive (not GitHub's autogenerated tag tarball, which has
# no stability guarantee) is what registries and archive_overrides should
# consume.

set -euo pipefail

TAG="$1"
VERSION="${TAG#v}"
PREFIX="onnxruntime_prebuilt-${VERSION}"
ARCHIVE="onnxruntime_prebuilt-${TAG}.tar.gz"

if ! grep -q "version = \"${VERSION}\"" MODULE.bazel; then
  echo "MODULE.bazel does not declare version ${VERSION}; bump it before tagging ${TAG}" >&2
  exit 1
fi

# -n keeps the gzip header timestamp-free so the archive is reproducible.
git archive --format=tar --prefix="${PREFIX}/" "${TAG}" | gzip -n > "${ARCHIVE}"

INTEGRITY="sha256-$(openssl dgst -sha256 -binary "${ARCHIVE}" | base64)"

cat <<EOF
## Using with bzlmod

\`\`\`starlark
bazel_dep(name = "onnxruntime_prebuilt", version = "${VERSION}")

onnxruntime = use_extension("@onnxruntime_prebuilt//extensions:onnxruntime.bzl", "onnxruntime")
onnxruntime.download(
    default = True,
    version = "1.24.4",
)
use_repo(onnxruntime, "onnxruntime", "onnxruntime-gpu")
\`\`\`

Until the version is available from the Bazel Central Registry, add:

\`\`\`starlark
archive_override(
    module_name = "onnxruntime_prebuilt",
    integrity = "${INTEGRITY}",
    strip_prefix = "${PREFIX}",
    urls = ["https://github.com/rimelabs/onnxruntime_prebuilt/releases/download/${TAG}/${ARCHIVE}"],
)
\`\`\`
EOF
